# Generated by Django 5.0.7 on 2024-09-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='users/default.jpeg', upload_to='users/%Y/%m/%d'),
        ),
    ]
