# Generated by Django 5.0.7 on 2024-07-27 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_disabled',
            field=models.BooleanField(default=False, help_text='Check to disable user account'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_instructor',
            field=models.BooleanField(default=False, help_text='Checked creates an instructor account'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
