# Generated by Django 5.0.7 on 2024-09-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
