# Generated by Django 5.0.7 on 2024-09-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_meeting_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
