# Generated by Django 5.0.7 on 2024-09-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_meeting_updated_alter_meeting_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='restrict_to_student',
            field=models.BooleanField(default=True),
        ),
    ]
