# Generated by Django 5.0.7 on 2024-09-23 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_meeting_restrict_to_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 23, 33, 7, 42933, tzinfo=datetime.timezone.utc)),
        ),
    ]
