# Generated by Django 5.0.7 on 2024-09-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_instructorprofile_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='institution',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
