# Generated by Django 5.0.7 on 2024-09-23 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_meeting_expires'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='restrict_to_student',
            new_name='only_enrolled_students',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 23, 35, 49, 903135, tzinfo=datetime.timezone.utc)),
        ),
    ]
