# Generated by Django 5.0.7 on 2024-09-23 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_restrict_to_student_meeting_only_enrolled_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='about_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 23, 43, 20, 274057, tzinfo=datetime.timezone.utc)),
        ),
    ]
