# Generated by Django 5.0.7 on 2024-09-24 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_meeting_about_message_alter_meeting_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 18, 7, 36, 591482, tzinfo=datetime.timezone.utc)),
        ),
    ]
