# Generated by Django 5.0.7 on 2024-10-01 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_meeting_meeting_name_alter_meeting_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 15, 11, 30, 253522, tzinfo=datetime.timezone.utc)),
        ),
    ]
