# Generated by Django 5.0.7 on 2024-10-01 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_meeting_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 16, 12, 52, 457128, tzinfo=datetime.timezone.utc)),
        ),
    ]
