# Generated by Django 5.0.7 on 2024-10-07 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_meeting_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='sch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='sch_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 10, 9, 55, 33, 177011, tzinfo=datetime.timezone.utc)),
        ),
    ]
