# Generated by Django 5.0.7 on 2024-10-07 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_meeting_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 10, 19, 27, 30, 803998, tzinfo=datetime.timezone.utc)),
        ),
    ]
