# Generated by Django 5.0.7 on 2024-10-08 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_meeting_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 11, 10, 15, 2, 920922, tzinfo=datetime.timezone.utc)),
        ),
    ]
