# Generated by Django 5.0.7 on 2024-10-13 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_profile_field_of_study_alter_meeting_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='field_of_study',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 16, 20, 9, 50, 803605, tzinfo=datetime.timezone.utc)),
        ),
    ]
