# Generated by Django 5.0.7 on 2024-10-13 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_profile_field_of_study_alter_meeting_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interest',
            field=models.CharField(choices=[('any', 'Any'), ('science', 'science'), ('mathematics', 'Mathematics'), ('cybersecurity', 'Cybersecurity'), ('programming', 'Programming')], default='any', max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 16, 20, 20, 29, 20036, tzinfo=datetime.timezone.utc)),
        ),
    ]
