# Generated by Django 5.0.7 on 2024-10-13 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_profile_interest_alter_meeting_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interest',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 16, 20, 25, 40, 539897, tzinfo=datetime.timezone.utc)),
        ),
    ]
