# Generated by Django 5.0.7 on 2024-10-20 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_meeting_expires_alter_profile_field_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 9, 43, 3, 307349, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_token',
            field=models.CharField(help_text='meeting token'),
        ),
    ]
