# Generated by Django 5.0.7 on 2024-10-20 10:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_delete_courseprogress'),
        ('users', '0027_alter_meeting_expires_alter_meeting_meeting_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 10, 19, 56, 818609, tzinfo=datetime.timezone.utc)),
        ),
    ]
