# Generated by Django 5.0.7 on 2024-10-20 10:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_delete_courseprogress'),
        ('users', '0028_alter_meeting_course_alter_meeting_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 10, 30, 56, 225394, tzinfo=datetime.timezone.utc)),
        ),
    ]
