# Generated by Django 5.0.7 on 2024-11-12 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_meeting_course_alter_meeting_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 15, 15, 16, 49, 350649, tzinfo=datetime.timezone.utc)),
        ),
    ]
