# Generated by Django 5.0.7 on 2025-01-08 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_meeting_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 11, 16, 44, 47, 935284, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_token',
            field=models.CharField(help_text='meeting token', max_length=30),
        ),
    ]
