# Generated by Django 5.0.7 on 2024-10-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='authorization_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
