# Generated by Django 5.0.7 on 2024-10-10 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_authorization_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWallet',
        ),
    ]
