# Generated by Django 5.0.7 on 2024-10-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_delete_userwallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='access_code',
            new_name='reference_code',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='authorization_url',
        ),
    ]
