# Generated by Django 5.0.7 on 2024-08-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='pass_score',
            field=models.IntegerField(default=90),
        ),
    ]
