# Generated by Django 5.0.7 on 2024-09-22 16:33

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [TrigramExtension()]
