# Generated by Django 5.0.7 on 2024-09-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certification',
            field=models.BooleanField(default=True),
        ),
    ]
