# Generated by Django 5.0.7 on 2024-09-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='images/default/default.jpg', upload_to='images/courses/%Y/%m/%d'),
        ),
    ]
