# Generated by Django 5.0.7 on 2024-07-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_price_course_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='images/default/default.jpg', upload_to='images'),
        ),
    ]
