# Generated by Django 5.0.7 on 2024-10-07 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_coupon_order_discountt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discountt',
            new_name='discount',
        ),
    ]
