# Generated by Django 5.0.7 on 2024-10-07 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_discountt_order_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount',
            new_name='discountt',
        ),
    ]
